config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, :controllers => { :registrations => 'registrations' }
  
  resources :articles

  resources :comments
  
  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author
  has_many :comments, as: :commentable, dependent: :destroy
  
  has_many :article_to_tags
  has_many :tags, through: :article_to_tags

  validates :title, :body, :image, presence: true
  validates :title, uniqueness: true
  validates :body, length: { in: 150..1000 }
end

app/models/article_to_tag.rb
class ArticleToTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :comments

  validates :username, :email, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true, length: { maximum: 100 }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_to_tags
  has_many :articles, through: :article_to_tags

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_author!, except: [:index, :show]
  include ArticlesHelper

  def index
    @articles = params[:tag] ? Tag.find_by_name(params[:tag]).articles.reverse :
                params[:author] ? Author.find_by_username(params[:author]).articles.reverse :
                Article.all.reverse
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_author.articles.build(article_params)

    respond_to do |format|
      if @article.save
        save_tags(@article, params[:article_tags])
        format.html { redirect_to articles_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new}
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update(article_params)
        save_tags(@article, params[:article_tags])
        format.html { redirect_to article_path(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :edit}
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path(:author => current_author.username)
  end
  
  private
  
  def article_params
    params.require(:article).permit(:title, :body, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_author!
  def create
    if params[:type] == 'Article'
      article = Article.find(params[:id])
      comment = article.comments.build(comment_params)
      comment.update(:author_id => current_author.id)
    else
      comment = Comment.find(params[:id])
      subComment = comment.comments.build(comment_params)
      subComment.update(:author_id => current_author.id)
    end
    redirect_to article_path(params[:article_id])
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to article_path(params[:article_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:author).permit(:avatar, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:author).permit(:avatar, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def save_tags(article, params)
    newTagArray = params.downcase.split(', ')
    oldTagArray = list_tags(article)

    newTagArray.reject!{ |tag| tag.empty? }

    remove_tags(article, oldTagArray - newTagArray)
    add_tags(article, newTagArray - oldTagArray)
  end

  def remove_tags(article, tagArray)
    tagArray.each do |tagName|
      tag = Tag.find_by_name(tagName)
      ArticleToTag.where(:article_id => article.id, :tag_id => tag.id).destroy_all
      check_destroy_tag(tag)
    end
  end

  def add_tags(article, tagArray)
    tagArray.each do |tagName|
      tag = Tag.find_by_name(tagName)
      tag = Tag.create(:name => tagName) unless tag
      ArticleToTag.create(:article_id => article.id, :tag_id => tag.id)
    end
  end

  def list_tags(article)
    article.tags.map { |tag| tag.name.downcase }
  end

  def check_destroy_tag(tag)
    if tag.articles.empty?
      tag.destroy
    end
  end
end

app/views/articles/_box.html.erb
<article class='<%= "tile is-child article #{boxClass} box p-2" %>'>

  <%= link_to 'Read more', article_path(article), class: 'button is-success is-light article__readme' %>
  <%= link_to article.author.username, articles_path(:author => article.author.username), class: 'button is-warning is-light article__author' %>

  <img class='article__image' src=<%= article.image %> alt=<%= article.title %>>
  <div class='article__inner'>
    <div class='article__title'><%= article.title %></div>
    <div class='article__body'><%= article.body %></div>
  </div>
</article>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%# Prevent submission when hit enter %>
  <button type="submit" disabled class="hidden" aria-hidden="true"></button>

  <div class="field">
    <div class="control">
    <%= f.input :title,
                required: true,
                autofocus: true,
                input_html: { class: "input" },
                label_html: { class: "label" },
                wrapper: false,
                error: false %>
    </div>
    <p class='<%= "help is-danger #{"hidden" if @article.errors[:title].empty?}" %>' id="article_title_error">Please enter a title of at least 10 characters</p>
  </div>

  <div class="field">
    <div class="control">
    <%= f.input :body,
                as: :text,
                required: true,
                autofocus: true,
                input_html: { class: "input editor__textarea" },
                label_html: { class: "label" },
                wrapper: false,
                error: false %>
    </div>
    <p class='<%= "help is-danger #{"hidden" if @article.errors[:body].empty?}" %>' id="article_body_error">Minimum 100, and maximum 500 characters</p>
  </div>

  <div class="field">
    <div class="control">
      <label for="image" class="label">Article Image</label>
      <div class="file">
        <label class="file-label is-full-width">
          <input class="file-input" type="file" id="upload_new_image">
          <%= f.input :image,
                      required: true,
                      autofocus: true,
                      input_html: { class: "hidden new_image" },
                      label: false,
                      wrapper: false,
                      error: false %>
          <span class="file-cta is-half-width">
            <span class="file-icon">
              <i class="fa fa-upload"></i>
            </span>
            <span class="file-label">
              Upload
            </span>
          </span>
          <button class="button is-danger file-cta-remove is-half-width" id="delete_article_image">Remove</button>
        </label>
      </div>
    </div>
    <p class='<%= "help is-danger #{"hidden" if @article.errors[:image].empty?}" %>' id="article_image_error">Please upload an image</p>
    <img class='mt-2' id="selected_image">
  </div>

  <div class="field">
    <div class="control">
      <%= label_tag "Tags (only alphanumeric characters)", nil, class: "label" %>
      <input type="text" class="input" id="tag_input" placeholder="Type comma to save">
      <div class="editor__tags-wrap my-2">
        <% if @article.tags %>
          <% @article.tags.each do |tag| %>
            <div class="editor__tag">
              <%= tag.name %>
              <div class="editor__removeTag">
                <i class="fal fa-times fa-sm"></i>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= hidden_field_tag :article_tags, @article.tags.map { |tag| tag.name }.join(', ') %>
    </div>
    <p class="help is-danger hidden" id="article_tags_length_error">Tags must have minimum 4 characters</p>
    <p class="help is-danger hidden" id="article_tags_exist_error">Tag already exists</p>
    <p class="help is-danger hidden" id="article_tags_error">Please enter at least one tag</p>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, "Publish", class: "button is-primary", id: "article_publish" %>
    </div>
  </div>
<% end %>

<%= javascript_pack_tag 'tagEditor' %>
<%= javascript_pack_tag 'imageEditor' %>
<%= javascript_pack_tag 'formValidator' %>

app/views/articles/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-6 is-offset-3">
        <%= render partial: 'articles/form' %>
        <br>
        <div class="field">
          <div class="control">
            <%= link_to "Take me back", :back, class: "button is-link" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/index.html.erb
<section class="section">
  <div class="container">
    <div class="tile is-ancestor is-vertical">
      
      <% @articles.each_with_index do |article, index| %>
        <%# Size of the articles alternates at each row %>
        <% size = ([2,3].include? index % 6) ? 1 : 2 %>
        <% start = [0,4].include? index % 6 %>
        <% finish = [1,5].include? index % 6 %>
        <% parentStart = index % 3 == 0 %>
        <% parentFinish = index % 3 == 2 %>

        <%# Check if parent should start%>
        <% if parentStart %><div class="tile is-parent is-12"><% end %>

        <%# Check if double row should start %>
        <% if start %><div class="tile is-parent is-vertical is-8"><% end %>

        <%# Depending on the size change style %>
        <% if size == 2 %>
          <%= render partial: 'articles/box', :locals => {:article => article, :boxClass => 'article--horizontal'} %>
        <% else %>
          <article class="tile is-parent is-4">
            <%= render partial: 'articles/box', :locals => {:article => article, :boxClass => 'article--vertical'} %>
          </article>
        <% end %>

        <%# Check if double row should end %>
        <% if finish %></div><% end %>

        <%# Check if parent should end%>
        <% if parentFinish %></div><% end %>
      <% end %>

      <%# Check if double row may not ended properly %>
      <% if [1,5].include? @articles.length % 6 %></div><% end %>

      <%# Check if parent did not ended properly %>
      <% if @articles.length % 3 != 2 %></div><% end %>

    </div>
  </div>
</section>

app/views/articles/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-6 is-offset-3">
        <%= render partial: 'articles/form' %>
        <br>
        <div class="field">
          <div class="control">
            <%= link_to "Take me back", :back, class: "button is-link" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">

        <% if author_signed_in? && @article.author == current_author %>
          <div class="field">
            <div class="control">
              <%= link_to 'Edit article', edit_article_path(@article), class: 'button is-warning' %>
              <%= link_to 'Delete article', article_path(@article), method: :delete, class: 'button is-danger' %>
            </div>
          </div>
        <% end %>

        <div class="field">
          <div class="control">
            <div class='article__title article--large-font'><%= @article.title %></div>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <div class="article__details">
              <p class="is-flex is-flex-wrap-wrap">
                <strong class='is-size-6'>
                  By <span class='has-text-link'><%= link_to @article.author.username, articles_path(:author => @article.author.username) %></span>
                </strong>
              </p>

              <p class="is-flex is-flex-wrap-wrap">
                <strong>Tags:</strong>
                <% @article.tags.each do |tag| %>
                  <%= link_to tag.name.capitalize, articles_path(:tag => tag.name), class: 'ml-2' %> 
                <% end %>
              </p>

              <p class="is-inline-flex"><strong class='mr-2'>Created:</strong> <%= @article.created_at.strftime("%d/%m/%Y %A %I:%M %p") %></p> | 
              <p class="is-inline-flex"><strong class='mr-2'>Updated:</strong> <%= ((Time.now - @article.updated_at)/3600).round %> hours ago</p>
            </div>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <img class='article__image' src=<%= @article.image %> alt=<%= @article.title %>>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <div class='article__body'><%= simple_format(@article.body) %></div>
          </div>
        </div>

        <section class="section p-0" id="comment__section">
          <% if author_signed_in? %>
            <%= render partial: 'comments/form', locals: {type: 'Article', article_id: @article.id, id: @article.id } %>
          <% end %>

          <%= render partial: 'comments/show', locals: {article: @article, parent: @article} %>
        </section>

      </div>
    </div>
  </div>
</section>

<%= javascript_pack_tag 'commentEditor' %>

app/views/comments/_form.html.erb
<article class="media">
  <div class="media-left">
    <figure class="image is-64x64">
      <img src='<%= current_author.avatar %>' alt='<%= current_author.username %>'>
    </figure>
  </div>
  <div class="media-content">
    <%= simple_form_for(Comment.new, html: {class: "is-relative"}) do |f| %>
      <%= hidden_field_tag "article_id", article_id %>
      <%= hidden_field_tag "type", type %>
      <%= hidden_field_tag "id", id %>
      <div class="field">
        <div class="control">
        <%= f.input :body,
                    required: true,
                    autofocus: true,
                    maxlength: 100,
                    input_html: { class: "input comment__input" },
                    label: false,
                    wrapper: false,
                    error: false %>
        </div>
      </div>

      <%= f.submit "Send", class: "button is-link is-small comment__button" %>
    <% end %>
  </div>
</article>

app/views/comments/_show.html.erb
<% parent.comments.reverse.each do |comment| %>
  <% if parent == article %>
    <section class="box p-1 comment__thread">
      <div style="margin-bottom: -1rem;">
  <% end %>

  <article class="media is-relative mb-4">
    <div class="media-left">
      <figure class="image is-64x64">
        <img src='<%= comment.author.avatar %>' alt='<%= comment.author.username %>'>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <strong><%= link_to comment.author.username, articles_path(:author => comment.author.username) %></strong>
        <small>(<%= comment.created_at.strftime("%d/%m/%Y %I:%M") %>)</small>
        <br />
        <p><%= comment.body %></p>
      </div>
    </div>

    <% if author_signed_in? %>
      <button class="button is-link is-small comment__button" name="comment__respond" id=<%= comment.id %>>
        <p class='not-mobile'>Respond</p>
        <p class='mobile'><i class="fal fa-pencil-alt"></i></p>
      </button>
    <% else %>
      <%= link_to new_author_session_path, class: "button is-link is-small comment__button" do %>
        <p class='not-mobile'>Sign in to respond</p>
        <p class='mobile'><i class="fal fa-pencil-alt"></i></p>
      <% end %>
    <% end %>

    <% if comment.author == current_author %>
      <%= link_to comment_path(comment.id, :article_id => article.id), method: :delete, class:"button is-link is-small comment__button comment__delete" do %>
        <i class="fal fa-trash-alt"></i>
      <% end %>
    <% end %>
  </article>

  <% if author_signed_in? %>
    <div class="ml-4 mb-5 hidden" name="comment__form" id='<%= "comment__form-#{comment.id}" %>'>
      <%= render partial: 'comments/form', locals: {type: 'Comment', article_id: article.id, id: comment.id } %>
    </div>
  <% end %>

  <% unless comment.comments.empty? %>
    <div class="ml-4">
      <%= render partial: 'comments/show', locals: {article: article, parent: comment} %>
    </div>
  <% end %>

  <% if parent == article %>
      </div>
    </section>
  <% end %>
<% end %>

app/views/common/_header.html.erb
<header class="header">
  <section class="section p-0 header__sub">
    <%= render partial: 'common/navbar' %>
  </section>

  <section class="section p-0 header__sub">
    <%= render partial: 'common/tagbar' %>
  </section>
</header>

app/views/common/_navbar.html.erb
<nav class="navbar navbar--orange-bg">
  <div class="container">
    <div class="navbar-brand pl-5">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">Blogster</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbar__menu">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div class="navbar-menu" id="navbar__menu">
      <div class="navbar-end">
        <p class="navbar-item py-0">
          <%= link_to 'New Article', new_article_path, class: "button is-full-width" %>
        </p>
        <% if author_signed_in? %>
          <p class="navbar-item py-0">
            <%= link_to 'My Articles', articles_path(:author => current_author.username), class: "button is-full-width" %>
          </p>
          <p class="navbar-item py-0">
            <%= link_to current_author.username, edit_author_registration_path, class: "button is-full-width" %>
          </p>
          <p class="navbar-item py-0">
            <%= link_to "Logout", destroy_author_session_path, method: :delete, class: "button is-full-width" %>
          </p>
        <% else %>
          <p class="navbar-item py-0">
            <%= link_to "Sign In", new_author_session_path, class: "button is-full-width" %>
          </p>
          <p class="navbar-item py-0">
            <%= link_to "Sign Up", new_author_registration_path, class: "button is-full-width" %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<%= javascript_pack_tag 'navbarToggle' %>

app/views/common/_tagbar.html.erb
<nav class="navbar navbar--orange-grey-bg is-flex-row-centered">
  <div class="navbar-item">
    <div class="field is-grouped tagbar">
      <% tags = Tag.all.reverse %>
      <% (tags.length < 20 ? tags.length : 20).times do |index| %>
        <p class="control">
          <%= link_to tags[index].name.capitalize, articles_path(:tag => tags[index].name), class: "button is-rounded tag__button" %>
        </p>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogster</title>
    <meta name="viewport" content="width=device-width, initial-scale=-1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://pro.fontawesome.com/releases/v5.15.2/css/all.css" %>
  </head>

  <body>
    <%= render partial: 'common/header' %>
    <%= yield %>
  </body>
</html>